In [1]:
import numpy as np

In [22]:
import numpy as np

marks = np.array([
    
        
            [70, 80, 90, 60, 75]
            
        
    ])

# (marks.ndim)
# (marks.shape)
(marks[0,1])

np.int64(80)

In [31]:
marks=np.array([
    [
    [12,13,14,15],
    [23,21,24,55],
],
    [
    [56,78,45,67],
    [23,45,67,12]
    ]
    ])
# marks.ndim    
marks.shape

(2, 2, 4)

In [33]:
arr=np.array([1,2,3,4,5,6])
print(arr.shape)

(6,)


In [35]:
data=np.array([
    [12,13,14,14,13],
    [34,45,567,78,89]
])

print(data.shape)
print(data.size)

(2, 5)
10


In [38]:
data=np.array([
    [1],
    [1]
    ])
print(data.dtype)

int64


In [46]:
data=np.array([10,20,30,40,50])
data1=[10,20,30,40,50]
print(data.ndim)
print(data.size)
print(data.shape)
print(data.dtype)
print(data) # np.array u can use to remove the commas to the output
print(data1)# commass are allowed

1
5
(5,)
int64
[10 20 30 40 50]
[10, 20, 30, 40, 50]


In [52]:
arr=np.array([
    [12,13,13,13,13],
    [45,67,79,76,56],
    [45,34,45,45,56,]

])
arr1=[12,13,13,13,13,
     45,67,79,76,56,
     45,34,45,45,56,]

print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr1)
# print(arr1.dtype)

(3, 5)
2
15
int64
[12, 13, 13, 13, 13, 45, 67, 79, 76, 56, 45, 34, 45, 45, 56]


In [54]:
data11=np.array([
    [
        [12,12,12,12,12,12],
        [12,12,12,12,12,12,]
    ],
    [
        [12,12,12,12,12,12],
        [12,12,12,12,12,12]
    ]
])
print(data11.shape)
print(data11.ndim)
print(data11.size)
print(data11.dtype)

(2, 2, 6)
3
24
int64


In [58]:
arr=np.arange(10,0,-1)
arr

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [66]:
arr=np.linspace(0,20,5)
print(arr)

[ 0.  5. 10. 15. 20.]


In [67]:
arra=np.eye(8)
print(arra)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [80]:
#randam variables

arr=np.random.rand(10)
print(arr)

[0.02559376 0.07732625 0.71368233 0.13834503 0.53362854 0.71579424
 0.16053621 0.71847687 0.36681049 0.69071375]


In [83]:
# shape
arr=np.random.rand(2,5)
print(arr)
print(arr.shape)
print(arr.ndim)

[[0.08170145 0.78291929 0.96621606 0.14039218 0.45260792]
 [0.91691002 0.26877256 0.31431601 0.73129638 0.27368461]]
(2, 5)
2


In [89]:
arr=np.array([
    # [True,False],
     [32.1,43.1,45.4]
    ] ,dtype=int)
print(arr.dtype
)
arr

int64


array([[32, 43, 45]])

In [ ]:
arr=np.array([12,23,45,56,78,89,78])
print(len(arr))
print(arr.size)
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])
print(arr[4])
print(arr[5])
print(arr[6])
# print(arr[7])
# negative  index also avaliable



7
7
12
23
45
56
78
89
78


In [134]:
arr=np.array([
    [1,2,3,4,5,6,7,8],
    [1,2,3,4,5,6,7,8],
    [1,2,3,4,5,6,7,8],

])
arr[0,1] = 99
print(arr)

[[ 1 99  3  4  5  6  7  8]
 [ 1  2  3  4  5  6  7  8]
 [ 1  2  3  4  5  6  7  8]]


In [138]:
arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])

print(arr[:2])

[[10 20 30 40]
 [50 60 70 80]]


In [10]:
import numpy as np
arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])
print(arr[2,:3])

[ 90 100 110]


In [11]:
arr[:2,:3]

array([[10, 20, 30],
       [50, 60, 70]])

In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60])
print(arr[-3:])
print(arr[::-1])


[40 50 60]
[60 50 40 30 20 10]


In [15]:
arr2=np.array([10, 20, 30, 40, 50, 60])

print(arr + arr2)

[ 20  40  60  80 100 120]


In [6]:
import numpy as np
arr= np.array([10, 20, 30, 40, 50, 60], dtype=int)
print(np.sqrt(arr))
# print(arr)

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781 7.74596669]


In [8]:
import numpy as np
arr = np.array([2, 3, 4])

print(np.power(arr[1], 2))

9


In [9]:
arr=np.array([-12,-45,3,56])
print(np.abs(arr))

[12 45  3 56]


In [13]:
arr.min()
print(arr.max())

56


In [14]:
arr = np.array([10.234, 20.678, 30.456])

print(np.round(arr, 2))

[10.23 20.68 30.46]


In [ ]:
import numpy as np

sales = np.array([100, 200, 300, 400, 500])

print(np.sum(sales))
print(np.mean(sales))
print(np.median(sales))
print(np.min(sales))
print(np.max(sales))

1500
300.0
300.0
100
500


In [19]:
data = np.array([10, 20, 30, 40, 50])
print(np.var(data))

200.0


In [29]:
a = np.array([48, 49, 50, 51, 52])
b = np.array([10, 30, 50, 70, 90])
# print(np.sum(a))
# print(np.sum(b))
# print(np.var(a))
# print(np.var(b))
print(np.std(a).round(4))
print(np.std(b).round(4))

1.4142
28.2843


In [36]:
arra=np.array([1,2,3,4,5,6,7,8,9,10])
new=arra.reshape(5,2)
print(new.shape)
print(new.size)

(5, 2)
10


In [42]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [1,2,3,]
])

print(arr.flatten())#flatten
print(arr.ravel())


[1 2 3 4 5 6 1 2 3]
[1 2 3 4 5 6 1 2 3]


In [ ]:
arr = np.array([10,20,30,40,50,60,70,80,90,100,110,120])
# print(arr.reshape(3,4))
# print(arr.reshape(4,-1)).
# print(arr.reshape(2,6))
# print(arr.reshape(6,2))


[[ 10  20]
 [ 30  40]
 [ 50  60]
 [ 70  80]
 [ 90 100]
 [110 120]]


In [52]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.append(a,b))

# result = np.hstack((a, b))

# print(result)

[1 2 3 4 5 6]


In [57]:
a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [5, 6],
    [7, 8]
])
# print(np.append(a,b))

# result= np.hstack((a,b))
# result= np.vstack((a,b))
result= np.concatenate((a,b))
result

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [59]:
# spilt
arr=np.array([1,2,3,4,5,6,7,8])
print(np.split(arr,4))

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [10]:
import numpy as np

arr= np.array([12,45,67,89,43,12])
arr1=np.where(arr>30,0,1)
arr1


array([1, 0, 0, 0, 0, 1])

In [14]:
data = np.array([23,45,56,4,2,45,])
arr1=np.where(arr>30,100,arr)
arr1[4]

np.int64(100)

In [17]:
arr1=np.array([30,50,60,70,80])
print(np.where(arr>40,"pass","fail"))

['fail' 'pass' 'pass' 'pass' 'pass' 'fail']


In [23]:
arr = np.array([10, 25, 40, 55, 70, 85])
arr1=np.where(arr==55,100,arr)
# print(arr1)
arr2=np.where(arr>=40,"pass","fail")
# print(arr2)
arr4=np.where(arr%2==0,0,arr)
print(arr4)

[ 0 25  0 55  0 85]


In [28]:
salary = np.array([20000, 35000, 50000, 18000, 70000])
arr1=np.where([salary>=30000] & [salary<30000],"high","low")
print(arr1)

TypeError: unsupported operand type(s) for &: 'list' and 'list'

In [38]:
arr=np.array([1,2,3,4,5,55423,46,4,57,78,656])
# arr1=np.removeDuplicates
print(np.sort(arr))

[    1     2     3     4     4     5    46    57    78   656 55423]


In [45]:
a = np.array([[30, 10, 20], [90, 50, 70]])
# print(np.sort(a, axis=1)) #sort each row
print(np.sort(a,axis=0)) # sort each column

[[30 10 20]
 [90 50 70]]


In [46]:
a = np.array([[30, 10, 20], [90, 50, 70]])
print(np.argsort(a))

[[1 2 0]
 [1 2 0]]


In [49]:
a = np.array([1,2,2,3,4])
b = np.array([3,4,4,5,6])
print(np.unique(a))
print(np.intersect1d(a,b))
print(np.union1d(a,b))
print(np.setdiff1d(a,b))
print(np.setxor1d(a,b))

[1 2 3 4]
[3 4]
[1 2 3 4 5 6]
[1 2]
[1 2 5 6]


In [50]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])
print(A * B)
print(A @ B)

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [52]:
a = np.array([[2,1],[1,3]])
b = np.array([5,6])
x = np.linalg.solve(a,b)
print(x)

[1.8 1.4]


In [54]:
a = np.array([10, np.nan, 30, np.inf])
print(np.isnan([a]))
print(np.isfinite(a))

[[False  True False False]]
[ True False  True False]


In [66]:
a = np.array([10,20,30,40])
b = a[1:3]
print(b)
b[0] = 999
print(a)
print(a)
# print(np.shares_memory(a,b))

[20 30]
[ 10 999  30  40]
[ 10 999  30  40]


In [65]:
a = np.array([10,20,30,40])
b = a[1:3].copy()
b[0] = 999
print(a)
print(b)
print(a)

[10 20 30 40]
[999  30]
[10 20 30 40]


In [2]:
data = np.array([(1, 'A', 50000), (2, 'B', 60000)],
dtype=[('id','i4'),('name','U10'),('salary','f8')])
print(data['salary'])

[50000. 60000.]


In [ ]:
import numpy as np
rng = np.random.default_rng(42)
n = 1000
order_id = np.arange(1, n + 1)
price = rng.uniform(100, 5000, n)
quantity = rng.integers(1, 6, n)
discount = rng.uniform(0, 0.40, n)
category_id = rng.integers(1, 6, n)
rating = rng.uniform(1, 5, n)
revenue = price * quantity * (1 - discount)
# revenue


# Your tasks:
# 1. Find total revenue.
# 2. Find average order revenue.
# 3. Find highest revenue order.
# 4. Find lowest revenue order.
# 5. Find the top 10 orders using argsort.
# 6. Label orders High/Low using np.where.
# 7. Find orders with discount > 30%.
# 8. Find unique category IDs.
# 9. Calculate average revenue per category.
# 10. Replace any artificial NaN/inf values safely.
# 11. Clip rating to [1, 5].
# 12. Standardize revenue.
# 13. Select top 20 orders using advanced indexing.
# 14. Explain every shape used.

# print(revenue)
# avg=revenue//n
# print(avg)

array([14231.69334425,  1385.78229788,  7336.20560225,  8757.2422208 ,
        1516.30502552,  3893.19031343,  8103.83090351,  3225.0587637 ,
        2660.10231269,  6476.99780774,  5449.03571962,  8544.9718817 ,
        2438.82823318, 14482.92148282,  5837.50450468,  2162.31910128,
        8078.04224058,  1019.51452189, 15594.8692442 ,  8827.57455926,
        6740.20861124,  5792.57177742, 12565.88605015,  9343.56782688,
        2805.36525316,  2939.6774514 ,  8181.70855708,  1272.1430907 ,
        2416.61631915,  6139.88314806,  9860.75048529,  4594.35035824,
        1323.14185963,  5500.51894554, 11668.33037123,  4152.46500703,
        1518.41957584,  1703.62225869,  4083.77691672,  8327.07829324,
        3012.30847371, 18887.86082544, 12086.5880398 ,  6062.28250196,
        6793.59841795, 17046.2586202 ,  5418.0991124 ,  3173.66354466,
       12047.37614889,  2796.59933773,  1023.0291194 ,   224.38007035,
        6953.05354156, 14308.9800424 , 12878.7718025 ,  5454.48689217,
      

In [18]:
import numpy as np 
ar=np.array([1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6])
aa1=np.unique_values(ar)
print(np.sort(aa1))



[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr = np.array([45, 12, 89, 34, 67, 23])
# print(np.sort(arr)[::-1])
# print(np.sort(arr))
# print(np.argmax(arr))
# print(np.argmin(arr))
# print(np.searchsorted(arr,3))

0


In [ ]:
a = np.array([10, 20, 30, 40, 50])
b = np.array([30, 40, 50, 60, 70])
# print(np.set(a,b))
# print(np.union1d(a,b))
# print(np.intersect1d(a,b))


[30 40 50]


In [24]:
arr=np.random.rand(5)
print(arr)

[0.23963118 0.804135   0.77692401 0.68260994 0.59341013]


In [41]:
arr=np.random.randint(1,20,5)

print(np.sort(arr))

[ 2  6  8 13 16]


In [68]:
arr = np.random.randint(1, 100, (3, 4))

print(np.sort(arr,axis=1))

[[ 9 18 64 96]
 [ 7 38 85 89]
 [63 67 92 92]]


In [74]:
# Randomly selects values from an existing array.

arr = np.array([10, 20, 30, 40, 50],dtype=float)

print(np.random.choice(arr))
print(np.random.choice(arr,2)) #Select multiple:

40.0
[40. 30.]


In [76]:
np.random.seed(42)

print(np.random.randint(1, 10, 5))

[7 4 8 5 7]


In [79]:
# Modern random API

# For advanced NumPy, you'll eventually see:

# from matplotlib.pylab import number


rng = np.random.default_rng(42)

arr = rng.integers(1, 10, 5)

print(arr)

# default_rng() is the modern recommended random-number interface.

# We'll revisit it in the advanced section.

[1 7 6 4 4]


In [103]:
# 🧪 Practice

arr=np.random.rand(6)
# print(arr)

arr1=np.random.randint(1,100,20)
# print(arr1)

arr1=np.random.randint(1,100,(3,3))
# print(arr1)

arr=np.array([20,20,30,405,6,7])
print(np.random.choice(arr,3))    

[405 405   6]


In [ ]:
# Array + scalar
import numpy as np

arr = np.array([10, 20, 30])

# print(arr + 50)
# print(arr-4)
# print(arr*5)
# print(arr//2)
# print(arr%5)
# print(arr**2)

[100 400 900]


In [ ]:

# 2d Array +scalar
a = np.array([
    [10, 20, 30], 
    [40, 50, 60]
])

b = np.array([1, 2, 3])

# print(a * b)
# print(a+20)
# print(a-b)
# print(a//b)
# print(a**b)

[[    10    400  27000]
 [    40   2500 216000]]


In [119]:
import numpy as np

A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print(A @ B)

[[19 22]
 [43 50]]


In [120]:
arr=np.array([
    [12,23,45,565],
    [12,34,56,67,]
    ])
print(arr.transpose())

[[ 12  12]
 [ 23  34]
 [ 45  56]
 [565  67]]


In [ ]:
marks = np.array([80, 90,np.nan , 70, 85])

# print(np.isnan(marks))



[False False  True False False]


In [126]:
arr = np.array([10, 20, np.nan, 40, np.nan])

print(np.sum(np.isnan(arr)))

2


In [127]:
x = np.inf

print(x)

inf


In [128]:
x = -np.inf

print(x)

-inf


In [129]:
arr = np.array([10, 20, np.inf, -np.inf])

print(arr)

[ 10.  20.  inf -inf]


In [132]:
prices = np.array([
    100,
    250,
    np.nan,
    500,
    np.inf,
    300
])

print(np.sum(np.isnan(prices)))

1


In [133]:
print(prices[np.isfinite(prices)])

[100. 250. 500. 300.]


In [141]:
import numpy as np
arr = np.array([
    10, 20, np.nan, 40, np.inf,
    60, np.nan, -np.inf, 80
])
# print(np.sum(np.isnan(arr)))
print(arr[~np.isnan(arr)])

[ 10.  20.  40.  inf  60. -inf  80.]


In [139]:
# print(np.sum(np.isinf(arr)))
# print(arr[~np.isnan(arr)])


In [142]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr.dtype)
print(arr.itemsize)

int64
8


In [143]:
ages = np.array(
    [21, 25, 30, 35, 40],
    dtype=np.int32
)

print("Elements:", ages.size)
print("Bytes per element:", ages.itemsize)
print("Total memory:", ages.nbytes)

Elements: 5
Bytes per element: 4
Total memory: 20


In [147]:
arr = np.array([10, 20, 30, 40, 50], dtype=np.int32)
print(arr.size)
print(arr.itemsize)
print(arr.nbytes)

5
4
20


In [4]:
import numpy as np
arr=np.array([1,2,3,4,5], dtype=np.int32)
print(arr.size)
print(arr.itemsize)
print(arr.nbytes)


5
4
20


In [5]:
import numpy as np
arr=np.array([1,2,3,4,5], dtype=np.int64)
print(arr.size)
print(arr.itemsize)
print(arr.nbytes)


5
8
40


In [6]:
import numpy as np

arr=np.array([1,2,3,4,5,6])
print(np.exp(arr))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]


In [7]:
x = np.array([-2, -1, 0, 1, 2])

sigmoid = 1 / (1 + np.exp(-x))

print(sigmoid)

[0.11920292 0.26894142 0.5        0.73105858 0.88079708]


In [ ]:
result = np.clip(marks, 0, 100)

print(result)

In [4]:
import numpy as np
salary = np.array([25000, 30000, 40000, 50000], dtype=int)

new_salary = salary * 1.10

print(new_salary)

[27500. 33000. 44000. 55000.]


In [9]:
marks = np.array([30, 60, 80, 40])
# vcheck= np.where(marks>=50,"pass","fail")
# vcheck

In [12]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

result = np.einsum('ij,jk->ik',A,B)
result

array([[19, 22],
       [43, 50]])

In [14]:
# Q1 — Vectorization
x = np.array([1, 2, 3, 4, 5])

# Calculate the cube of every value without a loop.

arr= x**3
arr

array([  1,   8,  27,  64, 125])

In [15]:
price = np.array([100, 200, 300])
quantity = np.array([2, 3, 4])

# Calculate each product's revenue.

revenue = price * quantity
revenue

array([ 200,  600, 1200])

In [19]:
# Q3 — np.vectorize()

# Create:

def check(x):
    if x >= 50:
        return "Pass"
    return "Fail"

# Apply it to:

marks = np.array([30, 55, 80, 40])

# using np.vectorize().

vcheck = np.vectorize(check)
result = vcheck(marks)
result
# print(np.dtype(result))

array(['Fail', 'Pass', 'Pass', 'Fail'], dtype='<U4')

In [21]:
# Q4 — einsum()

# Given:

a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

# Calculate the dot product using np.einsum().

# Expected:

# 140

result = np.einsum('ij,jk->ik', a, b)
result

ValueError: einstein sum subscripts string contains too many subscripts for operand 0

In [24]:
# Q5 — Linear Algebra
A = np.array([
    [1, 2],
    [3, 4]
])

# Find:

# determinant
# inverse
# eigenvalues

det= np.linalg.det(A)
print(det)

inverse= np.linalg.inv(A)
print(inverse)

values,eign= np.linalg.eig(A)
print(eign)

-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [28]:
# Q6 — Solve equations 🔥

# Solve:

# x + 2y = 5
# 3x + 4y = 11

# using:

# np.linalg.solve()

# Expected:

a=np.array([
    [1,2],
    [3,4]
])
b = np.array([5,11],dtype=int)

c=np.linalg.solve(a,b)
print("x:",
      c)
print("y:",
      c)

# x = 1
# y = 2

x: [1. 2.]
y: [1. 2.]


In [35]:
import numpy as np

np.random.seed(42)

x = np.random.randint(1, 100, 5)

print(x)

[52 93 15 72 61]


In [34]:
rng = np.random.default_rng(42)

x = rng.integers(1, 100, 5)

print(x)

[ 9 77 65 44 43]


In [32]:
rng = np.random.default_rng(42)

names = np.array(["A", "B", "C", "D"])

result = rng.choice(names, size=3)

print(result)

['A' 'D' 'C']


In [ ]:
A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

In [43]:
x = np.random.randint(1, 100, 5)
x

array([15, 62, 62, 47, 62], dtype=int32)

In [36]:
import numpy as np

data = np.array([
    ("Ravi", 25, 30000),
    ("Krishna", 28, 45000),
    ("Arjun", 24, 35000)
], dtype=[
    ("name", "U10"),
    ("age", "i4"),
    ("salary", "f8")
])
# print("salary"["salary" > 40000])
data[data["salary"] > 35000]
# print(data["name"])

array([('Krishna', 28, 45000.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('salary', '<f8')])

In [40]:
data = np.array([10, 20, -999, 40, -999, 60])
masked= np.ma.masked_equal(data,-999)
masked
print(np.sort(masked).mean())

32.5


In [47]:
date=np.datetime64("2026-10-06")
# end=np.datetime64("2026-10-01")
# result=date - end
time= date + np.timedelta64(30, "D")
print(time)

2026-11-05


In [22]:

# masked arrays allow you to handle missing or invalid data in NumPy arrays. You can create a masked array by specifying a condition that identifies the values to be masked. In this example, we will create a masked array that masks the value -999 in the data array.
import numpy as np

data = np.array([10, 20, -999, 40, 50,0,-5,4,-4,4545])  

masked = np.ma.masked_less(data, 0)
print(masked)
print(masked.mean())

# print(np.sort(masked))

[10 20 -- 40 50 0 -- 4 -- 4545]
667.0


In [23]:
import numpy as np

date = np.datetime64("2026-10-05")

print(date)

2026-10-05


In [24]:
np.timedelta64(5, "D")   # days
np.timedelta64(3, "h")   # hours
np.timedelta64(30, "m")  # minutes
np.timedelta64(20, "s")  # seconds

np.timedelta64(20,'s')

In [25]:
from numpy.polynomial import Polynomial

p = Polynomial([3, 2])

print(p(5))

13.0


In [27]:
p = Polynomial([5, 3, 2])
print(p(2))

19.0


In [28]:
p = Polynomial([5, 3, 2])

derivative = p.deriv()

print(derivative)

3.0 + 4.0 x


In [29]:
p = Polynomial([6, -5, 1])

print(p.roots())

[2. 3.]


fourier TRansforamer

In [52]:
import numpy as np

signal = np.array([1, 0, -1, 0])

result = np.fft.fft(signal)
magnitude = np.abs(result)
print(magnitude)

print(result)

[0. 2. 0. 2.]
[0.+0.j 2.+0.j 0.+0.j 2.+0.j]


In [ ]:
import time

start = time.time()
# print("Start time:", start)

Start time: 1791261008.7672198


NumPy + Pandas

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Sales": [100, 200, 300],
    "Profit": [20, 50, 80]
})

print(df)
sales = df["Sales"].to_numpy()

print(sales)
print(sales.mean())


   Sales  Profit
0    100      20
1    200      50
2    300      80
[100 200 300]
200.0


In [72]:
sales = np.array([100, 200, 300])
df=pd.DataFrame({
    "Sales": sales
    # "Profit":Profit
})
print(df)

   Sales
0    100
1    200
2    300


In [79]:
df=pd.DataFrame({
     "Sales": [5000, 15000, 8000, 20000]
})

df["Category"] = np.where(
    df["Sales"] <=4000,
    "High",
    "Low"
)
df[["Sales","Category"]]

,Sales,Category
0,5000,Low
1,15000,Low
2,8000,Low
3,20000,Low


In [89]:
df["Profit"] = np.array([500, 2000, 800, 3000], dtype=int)
df["Profit"]
df["Profit_Percentage"] = (
    df["Profit"] / df["Sales"]
) * 100
data=(df[["Sales", "Profit", "Profit_Percentage"]])
data

,Sales,Profit,Profit_Percentage
0,5000,500,10.000000
1,15000,2000,13.333333
2,8000,800,10.000000
3,20000,3000,15.000000
