In [2]:

import  numpy as np
marks = np.array([
    [80, 75, 90],
    [65, 70, 60],
    [95, 90, 92],
    [55, 60, 58]
])
marks

array([[80, 75, 90],
       [65, 70, 60],
       [95, 90, 92],
       [55, 60, 58]])

In [5]:
marks.shape
average=marks.mean(axis=1)
average

array([81.66666667, 65.        , 92.33333333, 57.66666667])

In [13]:
# Project 4 — Data Cleaning

data = np.array([
    10, 20, np.nan, 40,
    50, np.nan, 70
])

print(np.isnan(data))
clean = data[~np.isnan(data)]
print(clean)
# clean.mean()
np.nanmean(data)

[False False  True False False  True False]
[10. 20. 40. 50. 70.]


np.float64(38.0)

Project 5 — ML preprocessing

In [18]:
X = np.array([
    [10, 100],
    [20, 200],
    [30, 300],
    [40, 400]
])

mean = X.mean(axis=0)
std = X.std(axis=0)
print(mean)
print(std)

[ 25. 250.]
[ 11.18033989 111.80339887]


In [21]:
X_scaled = (X - mean) / std
X_scaled

array([[-1.34164079, -1.34164079],
       [-0.4472136 , -0.4472136 ],
       [ 0.4472136 ,  0.4472136 ],
       [ 1.34164079,  1.34164079]])